version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/djangocicd/
permissions:
   - object: /home/ubuntu/djangocicd/
     owner: root
     group: root
     mode: 003
hooks:
   BeforeInstall:
      - location: scripts/install.sh
        timeout: 300
        runas: root
   # ApplicationStart:
   #  - location: scripts/start_server
   #    timeout: 300
   #    runas: root
