version: 0.0
os: linux
files:
   - source: .
     destination: /home/ubuntu/djangocicd/
hooks:
   BeforeInstall:
      - location: setup.sh
        timeout: 300
        runas: root
   AfterInstall:
      - location: run.sh
        timeout: 300
        runas: root
