version: "3.7"

services:
   # db:
   #    build:
   #       context: .
   #       dockerfile: ./db/Dockerfile
   #    command: "--default-authentication-plugin=mysql_native_password"
   #    container_name: database
   #    ports:
   #       - "3306:3306"
   #    restart: always
   #    environment:
   #       - MYSQL_USER=root
   #       - MYSQL_ROOT_PASSWORD=root
   #       - MYSQL_DB=codejee_dev
   #    volumes:
   #       - ./db:/docker-entrypoint-initdb.d/:ro
   #       - ./db:/db
   #    networks:
   #       - codejee

   # phpmyadmin:
   #    links:
   #       - db
   #    depends_on:
   #       - db
   #    image: phpmyadmin/phpmyadmin
   #    container_name: "phpadmin"
   #    restart: always
   #    ports:
   #       - 8080:80
   #    environment:
   #       PMA_HOST: db
   #       MYSQL_ROOT_PASSWORD: root
   #    networks:
   #       - codejee

   backend:
      restart: always
      container_name: backend
      build:
         context: .
         dockerfile: ./docker/backend/Dockerfile
      entrypoint: /app/docker/backend/wsgi-entrypoint.sh
      ports:
         - "8000:8000"
      volumes:
         - ./backend/:/app/backend
         - static_volume:/app/backend/django_static
      expose:
         - 8000
      env_file:
         - ./backend/.env.dev
      networks:
         - codejee

   # frontend:
   #    restart: always
   #    container_name: frontend
   #    build:
   #       context: .
   #       dockerfile: ./docker/frontend/Dockerfile
   #    volumes:
   #       - ./frontend/:/app/frontend
   #       - /app/frontend/node_modules
   #       - /app/frontend/.next
   #    ports:
   #       - 3000:3000
   #    environment:
   #       - CHOKIDAR_USEPOLLING=true
   #    links:
   #       - db
   #    depends_on:
   #       - db
   #       - backend
   #    networks:
   #       - codejee

volumes:
   db:
   static_volume: {}

networks:
   codejee:
